# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='useremail',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
