# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0002_auto_20161207_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
